# permissions for end users to edit kubeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecluster-editor-role
rules:
- apiGroups:
  - networking.networking.aks.io
  resources:
  - kubeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.networking.aks.io
  resources:
  - kubeclusters/status
  verbs:
  - get
