# permissions for end users to view kubeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecluster-viewer-role
rules:
- apiGroups:
  - networking.aks.io
  resources:
  - kubeclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.aks.io
  resources:
  - kubeclusters/status
  verbs:
  - get
